twatter-soen341/Twatter

- names.md
I added my personal informations to the names.md file
> Added personnal info to names.md

- names.md
> Added my Info

- Features.md
- names.md
Added some of my ideas for extra features on the platform
> Added Features

- Features.md
> Alexandria info

- Features.md
- names.md
> Initial commit

- Features.md
- names.md
Hi, this is my initial pull request test. I just added my info to the team log and my ideas for the features.
> Added my ideas for features and my name and info to team log.

- README.md
> #34: update readme for all

- controllers/authController.js
- middleware/passport.js
- models/user.js
- package.json
- routes/auth.js
- server.js
Added authentication services for the backend to allow a user to login, signup and persist info in mongodb.
> #35 Added backend authentication services

- controllers/authController.js
- middleware/passport.js
- models/user.js
- package.json
- routes/auth.js
- server.js
- twatter-ui/src/app/app-routing.module.ts
- twatter-ui/src/app/app.component.ts
- twatter-ui/src/app/guards/loggedIn.guard.ts
- twatter-ui/src/app/header/header.component.html
- twatter-ui/src/app/header/header.component.scss
- twatter-ui/src/app/header/header.component.ts
- twatter-ui/src/app/login/login.component.html
- twatter-ui/src/app/login/login.component.ts
The guards will prevent people from accessing restricted areas of the website.
> #62 Added Guards for the Front-end endpoints

- package.json
- twatter-ui/src/app/app.module.ts
- twatter-ui/src/app/feed/posts/post-create/post-create-dialog.component.html
- twatter-ui/src/app/feed/posts/post-create/post-create.component.html
- twatter-ui/src/app/feed/posts/post-create/post-create.component.scss
- twatter-ui/src/app/feed/posts/post-create/post-create.component.ts
- twatter-ui/src/app/feed/posts/post-list/post-list.component.html
- twatter-ui/src/app/feed/posts/post-list/post-list.component.scss
- twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
- twatter-ui/src/app/header/header.component.html
- twatter-ui/src/app/header/header.component.scss
- twatter-ui/src/app/header/header.component.ts
- twatter-ui/src/app/models/post.model.ts
- twatter-ui/src/app/services/post.service.ts
- Added scrollbar
- Changed Avatar
- Added proper user info
> #61 Made user create- and list- posts more user friendly

- .github/ISSUE_TEMPLATE/user-story-issue-template.md
Added default labels for story points and priority.
> #75 Update issue templates

- controllers/auth.js
- controllers/user.js
- models/auth.js
- models/user.js
- routes/auth.js
- routes/user.js
- server.js
- twatter-ui/src/app/feed/posts/post-create/post-create.component.ts
- twatter-ui/src/app/header/header.component.ts
- twatter-ui/src/app/models/post.model.ts
- twatter-ui/src/app/services/auth.service.ts
- twatter-ui/src/app/services/user.service.spec.ts
- twatter-ui/src/app/services/user.service.ts
+ Split the auth model to have a separate user model.
+ Added search endpoints to search a user by name
+ refactored frontend to accomodate the changes to the backend
>  #72 Separated user and auth model

- controllers/twatController.js
- models/twat.js
- package.json
- routes/twatRoute.js
- server.js
Trying to resolve conflicts and errors Tarek is having with the back-end.
> Merge for Tarek to be up to date with backend changes

- controllers/twatController.js
- models/twat.js
- routes/twatRoute.js
* added new routes (CRUD) 
* improved the twat model (a.k.a the post)
* improved logics inside the controller
> improvement of the routes, model and controller

- controllers/twatController.js
- routes/twatRoute.js
* fixed issue where there was a typo related with the update route causing an error to happen
> fixed issue with update route

- controllers/twatController.js
Minor change in the way we store the timestamp at creation.
> Issue #51: Made the timestamp to store time on creation of the post 

- twatter-ui/src/app/header/header.component.html
- twatter-ui/src/app/profile/sidebar/sidebar.component.html
- twatter-ui/src/app/profile/sidebar/sidebar.component.scss
#52 
- Changed home and settings buttons to icons
#57 
- Added a container for user info under user picture in the sidebar
> #52 #57 Minor visual changes

- controllers/twatController.js
- routes/twatRoute.js
- twatter-ui/src/app/app-routing.module.ts
- twatter-ui/src/app/app.module.ts
- twatter-ui/src/app/feed/posts/post-list/post-list.component.html
- twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
- twatter-ui/src/app/feed/twatline/twatline.component.html
- twatter-ui/src/app/feed/twatline/twatline.component.spec.ts
- twatter-ui/src/app/feed/twatline/twatline.component.ts
- twatter-ui/src/app/profile/profile.component.html
- twatter-ui/src/app/profile/profile.component.ts
- twatter-ui/src/app/services/post.service.ts
- Changes in the API in order to receive posts filtered by user (changes in twatController, twatRoute, post.service)
- Few changes in the feed folder in order to reuse the post-list component to display posts in the profile
(twatline component, post-list.ts/html, app-routing, app.module)
- Re-using the post-list component and filtering the posts (profile.component.html/ts)
> #57 Display list of twats in user profile

- controllers/twatController.js
- controllers/user.js
- twatter-ui/src/app/feed/posts/post-create/post-create.component.ts
- twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
- twatter-ui/src/app/feed/twatline/twatline.component.html
- twatter-ui/src/app/feed/twatline/twatline.component.scss
- twatter-ui/src/app/feed/twatline/twatline.component.ts
- twatter-ui/src/app/header/header.component.html
- twatter-ui/src/app/models/post.model.ts
- twatter-ui/src/app/profile/profile.component.ts
- twatter-ui/src/app/services/post.service.ts
* Modified the edit post service to populate the user's field to get the information of the edited post.
* Added a method to format the date before displaying it
* Cleaned up the console logs
> #113 Fixed bug where the user's name would not display

- twatter-ui/src/app/feed/posts/post-list/post-list.component.html
- twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
- twatter-ui/src/app/header/header.component.html
- twatter-ui/src/app/header/header.component.scss
- Cleaned up header
- Added Notification Icon
- Included user's displayed name to the avatar's event
- Restricted Edit and Delete button to the user that created the post.
> #115 #93 Added Notification icon and post restrictions

- twatter-ui/src/app/app.component.html
- twatter-ui/src/app/feed/twatline/twatline.component.html
- twatter-ui/src/app/header/header.component.scss
- twatter-ui/src/app/profile/profile.component.html
changing to position sticky to fix some issues with overlapping, also refactored the header to be used from app component so it doesnt need to be reloaded between routes
> #61 Refactored app-header to be useful in all components

- controllers/twatController.js
- twatter-ui/src/app/feed/posts/post-create/post-create.component.ts
- twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
- twatter-ui/src/app/services/post.service.ts
* Modified the backend to sort by date before sending out the tweets.
* Modified frontend to unshift instead of push the new created posts
> #58 Modified service and post create to sort tweets by timestamp

- twatter-ui/src/app/feed/posts/post-create/post-create-dialog.component.html
- twatter-ui/src/app/feed/posts/post-create/post-create.component.html
- twatter-ui/src/app/feed/posts/post-create/post-create.component.scss
- twatter-ui/src/app/feed/posts/post-create/post-create.component.ts
- twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
Allows user to temporarily store their post content before officially posting it.
> #70 Modified Post Create

- twatter-ui/src/app/feed/posts/post-create/post-create.component.ts
- twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
Updated userId in post after user edits post.
> #115 Updated Restrictions

- .idea/workspace.xml
- twatter-ui/src/app/app.module.ts
- twatter-ui/src/app/feed/posts/post-create/post-create.component.html
- twatter-ui/src/app/feed/posts/post-create/post-create.component.scss
- twatter-ui/src/app/feed/posts/post-list/post-list.component.html
- twatter-ui/src/app/header/header.component.html
- twatter-ui/src/app/header/header.component.scss
- twatter-ui/src/app/header/header.component.ts
- twatter-ui/src/app/profile/profile.component.scss
Fixed some bugs where some icons would not appear in the header, the header would not be fixed and refactored the way icon colours are applied (will be easier to deal with later on).
> Fixing Bug #126 Where elements in the header would not appear correctly.

- twatter-ui/src/app/feed/posts/comment/comment.component.scss
User can comment what he thinks of a post. the comment will appear under the original post. The user can NOT edit or delete at the moment. Will be implemented afterwards
> #129 Finished Core commenting feature

- controllers/twatController.js
- models/twat.js
- routes/user.js
- twatter-ui/src/app/app.module.ts
- twatter-ui/src/app/feed/posts/comment/comment.component.html
- twatter-ui/src/app/feed/posts/comment/comment.component.scss
- twatter-ui/src/app/feed/posts/comment/comment.component.ts
- twatter-ui/src/app/feed/posts/post-create/post-create.component.scss
- twatter-ui/src/app/feed/posts/post-list/post-list.component.html
- twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
- twatter-ui/src/app/feed/twatline/twatline.component.html
- twatter-ui/src/app/services/user.service.ts
The first Pr was FROM dev to my branch... Essentially deleting everything
> #129 user story comment (Third time's the charm)

- twatter-ui/src/app/feed/posts/comment/comment.component.html
- twatter-ui/src/app/feed/posts/comment/comment.component.scss
- twatter-ui/src/app/feed/posts/comment/comment.component.ts
- twatter-ui/src/app/feed/posts/post-list/post-list.component.html
- twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
The user can now delete his comments or the comments of others if they are on his post.
> #141 #142 Can now delete comments

- .github/ISSUE_TEMPLATE/user-story-acceptance-test-template.md
- .github/ISSUE_TEMPLATE/user-story-issue-template.md
Added a template for Acceptance Test issues
> #158  Update issue templates

- .github/ISSUE_TEMPLATE/user-story-acceptance-test-template.md
Added Label Acceptance Test,
Removed extra breakline
> #158 Update issue templates

- twatter-ui/src/app/feed/posts/comment/comment.component.html
- twatter-ui/src/app/feed/posts/comment/comment.component.scss
- twatter-ui/src/app/feed/posts/comment/comment.component.ts
- twatter-ui/src/app/feed/posts/post-list/post-list.component.html
- twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
User can now modify his comments
> #143 #144 Can modify comments

- twatter-ui/src/app/app.module.ts
- twatter-ui/src/app/feed/posts/post-list/post-list.component.html
- twatter-ui/src/app/icons/twat-icon-btn/twat-icon-btn.component.html
- twatter-ui/src/app/icons/twat-icon-btn/twat-icon-btn.component.scss
- twatter-ui/src/app/icons/twat-icon-btn/twat-icon-btn.component.ts
The user can now see who liked his post. This will display the name of those who liked it. If no one liked it yet, it will display "No one loves you". This can be changed.
> #83 #92 Added the ability to view who liked your posts

- twatter-ui/src/app/app-routing.module.ts
- twatter-ui/src/app/feed/posts/post-list/post-list.component.html
- twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
- twatter-ui/src/app/header/header.component.html
- twatter-ui/src/app/header/header.component.ts
- twatter-ui/src/app/profile/profile.component.scss
- twatter-ui/src/app/profile/profile.component.ts
- twatter-ui/src/app/profile/sidebar/sidebar.component.html
- twatter-ui/src/app/profile/sidebar/sidebar.component.ts
- twatter-ui/src/app/services/user.service.ts
Can access other user's profile
> #164 #165 #166 Access other user's profile

- controllers/twatController.js
- controllers/user.js
- twatter-ui/package.json
- twatter-ui/src/app/app.component.scss
- twatter-ui/src/app/app.module.ts
- twatter-ui/src/app/feed/posts/comment/comment.component.html
- twatter-ui/src/app/feed/posts/comment/comment.component.scss
- twatter-ui/src/app/feed/posts/post-list/post-list.component.html
- twatter-ui/src/app/feed/posts/post-list/post-list.component.scss
- twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
- twatter-ui/src/app/header/header.component.scss
- twatter-ui/src/app/icons/twat-icon-btn/twat-icon-btn.component.html
- twatter-ui/src/app/icons/twat-icon-btn/twat-icon-btn.component.scss
- twatter-ui/src/app/icons/twat-icon-btn/twat-icon-btn.component.ts
- twatter-ui/src/app/profile/profile.component.ts
- twatter-ui/src/app/search/search-bar/search-bar.component.ts
- twatter-ui/src/app/search/search-results/search-results.component.html
- twatter-ui/src/app/search/search-results/search-results.component.scss
- twatter-ui/src/app/search/search-results/search-results.component.ts
- twatter-ui/src/app/services/user.service.ts
- twatter-ui/src/styles.scss
- twatter-ui/src/twatter-default-style.scss
- Updated logic to display carousel in search-result
- Changed primary color to red; added custom theming
- Styled general look; mostly colours and cursor types.
> #148 Modified search results and #61 minor styling .

- controllers/twatController.js
- controllers/user.js
- twatter-ui/src/app/feed/posts/post-list/post-list.component.html
- twatter-ui/src/app/feed/posts/post-list/post-list.component.ts
- twatter-ui/src/app/search/search-bar/search-bar.component.ts
- twatter-ui/src/app/search/search-results/search-results.component.html
- twatter-ui/src/app/search/search-results/search-results.component.scss
- twatter-ui/src/app/search/search-results/search-results.component.ts
- twatter-ui/src/app/services/post.service.ts
- twatter-ui/src/styles.scss
Added tabs to the search results page
Added posts also
Modified the post-list component to have the option of a simplified card and a limit of posts
>  #148 Added posts to the search result page

- twatter-ui/src/app/app-routing.module.ts
> Changed FollowingPost to FollowingPostComponent #60

- controllers/user.js
- twatter-ui/src/app/feed/following-post/following-post.component.html
- twatter-ui/src/app/feed/following-post/following-post.component.ts
- twatter-ui/src/app/follow-button/follow-button.component.ts
Title changes on whether the user is following someone or following no one. 
Only the last post that the users that the current user is following
> Bugfixes related to viewing following posts from profile #186

- controllers/auth.js
- routes/auth.js
- routes/user.js
- tests/test.js
User needs to be logged in to change email.
User needs to be logged in AND provide the old password to change password.
> #132 Added backend routes to change password and email

- controllers/auth.js
- controllers/user.js
- models/user.js
updating the user with a bio will add/update the field in the database.
> #227 Added Bio to user model in backend

- twatter-ui/src/app/app.module.ts
- twatter-ui/src/app/profile/display-user-list/display-user-list.component.html
- twatter-ui/src/app/profile/display-user-list/display-user-list.component.spec.ts
- twatter-ui/src/app/profile/display-user-list/display-user-list.component.ts
- twatter-ui/src/app/profile/sidebar/sidebar.component.html
- twatter-ui/src/app/profile/sidebar/sidebar.component.ts
- Created a component that lists a users first name and last name
- Added 2 instanced of that component in the sidebar in order to display the followers and the followed users of a user (in profile page)
> Update profile UI to display users #90

- controllers/auth.js
If the user is deleted, his twats now get deleted also. 
This will help with the tests since the twats weren't getting deleted.
> #132 Updated controller to delete a user

- twatter-ui/src/app/components/feed/twats/comment/comment.component.html
- twatter-ui/src/app/components/feed/twats/comment/comment.component.ts
- twatter-ui/src/app/components/feed/twats/twat-create/twat-create-dialog.component.html
Button is enbaled once user wrties a comment.
spaces only does not enable the button
> #239 Disabled comment button when there is no text

- backend/.eslintrc.json
- backend/controllers/auth.js
- backend/controllers/twatController.js
- backend/controllers/user.js
- backend/package.json
- backend/routes/user.js
- backend/tests/test.js
corrected the lint mistakes, generate a report for the final presentation
> #274 refactor lint problems, leave 1 or 2 to shoe lint report
